language: php

php:
  - 7.1
  - 7.2
  - 7.3
  # php8 is not supported yet
  #- nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-ansi --no-progress --no-suggest"

matrix:
  fast_finish: true
    #allow_failures:
  #- php: nightly

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

cache:
  directories:
    - $HOME/.composer/cache